<a href="https://colab.research.google.com/github/Sharma-Pranav/DeepLearning/blob/master/pytorch_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
def activation(x):
  return 1/(1 + torch.exp(-x))

In [0]:
torch.manual_seed(7) # random number seed

#Features are random normal variables
features = torch.randn((1,5))

# Weights for data
weights = torch.randn_like(features)

# Bias
bias = torch.randn((1,1))

In [0]:
y = activation(torch.sum(features * weights) + bias)
y_ = activation((features*weights).sum() + bias)

In [5]:
y

tensor([[0.1595]])

In [6]:
y_

tensor([[0.1595]])

In [0]:
# This is well and good but we need fast execution (vectorisation like numpy) or matrix operations.
#weights.view(a, b) will return a new tensor with the same data as weights with size (a, b).
y = activation(torch.mm(features, weights.view(5,1)) + bias)

In [8]:
y

tensor([[0.1595]])

In [0]:
features = torch.randn((1,3))
n_input = features.shape[1]
n_hidden = 2
n_output = 1
w1 = torch.randn(n_input, n_hidden)
w2 = torch.randn(n_hidden, n_output)

b1 = torch.randn((1, n_hidden))
b2 = torch.rand((1, n_output))


In [10]:
hidden_layer = activation(torch.mm(features, w1) + b1)
output = activation(torch.mm(hidden_layer, w2) + b2)
print(output)

tensor([[0.8107]])


In [11]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.97354371, 0.25337789, 0.57306716],
       [0.11069056, 0.49353788, 0.17982686],
       [0.2378132 , 0.84862626, 0.59486955],
       [0.6930289 , 0.0884995 , 0.82592602]])

In [12]:
b = torch.from_numpy(a)
b

tensor([[0.9735, 0.2534, 0.5731],
        [0.1107, 0.4935, 0.1798],
        [0.2378, 0.8486, 0.5949],
        [0.6930, 0.0885, 0.8259]], dtype=torch.float64)

In [13]:
b.numpy()

array([[0.97354371, 0.25337789, 0.57306716],
       [0.11069056, 0.49353788, 0.17982686],
       [0.2378132 , 0.84862626, 0.59486955],
       [0.6930289 , 0.0884995 , 0.82592602]])

In [15]:
# multiply elements of b
b.mul_(2)

tensor([[1.9471, 0.5068, 1.1461],
        [0.2214, 0.9871, 0.3597],
        [0.4756, 1.6973, 1.1897],
        [1.3861, 0.1770, 1.6519]], dtype=torch.float64)

In [16]:
# as the weights are shared between a and b, a will also multiplied
a

array([[1.94708742, 0.50675578, 1.14613432],
       [0.22138111, 0.98707576, 0.35965372],
       [0.47562639, 1.69725253, 1.1897391 ],
       [1.3860578 , 0.176999  , 1.65185204]])